name: clay_navier_stokes
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21
  - scipy>=1.7
  - matplotlib>=3.4
  - h5py>=3.6
  - pytest>=7.0
  - pip
  - pip:
    - -r requirements.txt
