name: navier-stokes-qcal
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy>=1.21.0
  - scipy>=1.7.0
  - matplotlib>=3.4.0
  - jupyter>=1.0.0
  - pip>=21.0
  - pip:
    - pytest>=6.2.0
