name: lean-ci
on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- -y
      - run: ~/.elan/bin/lake build
      - name: Allow sorry in purge_axioms
        if: contains(github.ref, 'purge_axioms')
        run: echo "allow_sorry branch; skipping #print axioms gate"
      - name: No extra axioms (main branches)
        if: "!contains(github.ref, 'purge_axioms')"
        run: |
          ~/.elan/bin/lake exe print-axioms RiemannAdelic | tee axioms.txt
          ! grep -E ".+" axioms.txt || (echo "Found axioms"; cat axioms.txt; exit 1)
