name: lean-ci

on:
  push:
    branches: [ main, purge_axioms ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Lean
      uses: leanprover/lean-setup@v1
      with:
        lean-version: 'lean4:stable'
        
    - name: Create lakefile if missing
      run: |
        if [ ! -f lakefile.lean ] && [ ! -f lakefile.toml ]; then
          echo "Creating minimal lakefile.lean"
          cat > lakefile.lean << 'EOF'
          import Lake
          open Lake DSL
          package NavierStokesQCAL
          require mathlib from git
            "https://github.com/leanprover-community/mathlib4.git"
          @[default_target]
          lean_lib NavierStokes
          EOF
        fi
        
    - name: Build project
      run: lake build
      
    - name: Run tests (if any)
      run: lake test || echo "No tests configured"
