name: lean-ci

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Lake/LEAN
        uses: actions/cache@v4
        with:
          path: |
            ~/.elan
            .lake
            lake-packages
          key: ${{ runner.os }}-lean-${{ hashFiles('lean-toolchain') }}-${{ hashFiles('lakefile.lean', 'lake-manifest.json') }}
          restore-keys: |
            ${{ runner.os }}-lean-

      - name: Install Lean (elan)
        run: |
          bash Scripts/setup_lean.sh
        shell: bash

      - name: Build (lake)
        run: |
          bash Scripts/build_lean_proofs.sh
        shell: bash

      - name: Check no-sorry
        run: |
          bash Scripts/check_no_sorry.sh
        shell: bash

      - name: Lint
        run: |
          bash Scripts/lint.sh
        shell: bash
